# Visualizer params
Visualizer:
  Camera: 
      dist: 1.3
      position: [0.6, 0.6, 0.85]
      yaw: 95.6
      pitch: -31.6

# Robot params
Robot:
  base_init_pose: [1, 0.1, 0, 0.0, 0.0, "math.pi / 2"]
  arm_reset_jointValues: [0.98, 0.458, 0.31, -2.24, -0.30, 2.66, 2.32]                  # The initial angle of arm joint
  arm_urdf_path: "Asset/Robot/mobile_manipulator/arm/franka/urdf/panda.urdf"          # arm urdf
  arm_num_dofs: 7                                      # 7 DOF
  eef_id: 11