# Client parameters
Client:
  enable_Debug: False

# Visualizer params
Visualizer:
  Camera: 
      dist: 2.0
      position: [1.15, 0.21, 1.07]
      yaw: -85.6
      pitch: -17.5

# Robot params
Robot:
  arm_reset_jointValues: [0.147, 0, -0.062, 1.561, -0.215, 0.009, -0.062]
  arm_urdf_path: "Asset/Robot/mobile_manipulator/arm/flexiv/urdf/flexiv_rizon4_robotiq_2f85.urdf"          # arm urdf
  arm_num_dofs: 7                                      # 7 DOF
  eef_id: 7